/**
 * Серверы Arizona RP (мини-апп: выбор в форме). Обновлять по списку с сервера.
 * Формат: "№ | ИМЯ" — как в игре/от заказчика.
 */
export const ARIZONA_RP_SERVER_OPTIONS: string[] = [
  "0 | Vice City",
  "1 | Phoenix",
  "2 | Tucson",
  "3 | Scottdale",
  "4 | Chandler",
  "5 | Brainburg",
  "6 | Saint Rose",
  "7 | Mesa",
  "8 | Red Rock",
  "9 | Yuma",
  "10 | Surprise",
  "11 | Prescott",
  "12 | Glendale",
  "13 | Kingman",
  "14 | Winslow",
  "15 | Payson",
  "16 | Gilbert",
  "17 | Show Low",
  "18 | Casa Grande",
  "19 | Page",
  "20 | Sun City",
  "21 | Queen Creek",
  "22 | Sedona",
  "23 | Holiday",
  "24 | Wednesday",
  "25 | Yava",
  "26 | Faraway",
  "27 | Bumble Bee",
  "28 | Christmas",
  "29 | Mirage",
  "30 | Love",
  "31 | Drake",
  "32 | Space",
];
